//Write your function calls below this line
setColor(0,0, "navy");
setColor(1,1, "navy");
setColor(2,2, "navy");
setColor(3,3, "navy");
setColor(4,4, "navy");
setColor(4,3, "navy");
setColor(4,2, "navy");
setColor(4,1, "navy");
setColor(5,2,"navy");
setColor(5,1, "red");
setColor(6,2, "red");
setColor(6,3,"navy");
setColor(7,4,"navy");
setColor(8,5,"navy");
setColor(8,4,"navy");
setColor(7,3,"red");
setColor(8,3, "navy");
setColor(8,2, "navy");
setColor(8,1, "navy");
setColor(8,0, "navy");
setColor(1,0, "red");
setColor(2,0, "red");
setColor(2,1, "red");
setColor(3,0, "red");
setColor(3,2, "red");
setColor(4,0, "red");
setColor(5,0, "red");
setColor(6,0, "red");
setColor(7,0, "red");
setColor(7,2, "red");
setColor(7,1, "red");
